[versions]
android-appcompat = "1.7.1"
android-compileSdk = "36"
android-constraintlayout = "2.2.1"
android-gradlePlugin = "9.0.0"
detekt = "1.23.7"
dokka = "2.1.0"
jacoco = "0.8.14"
kotlin = "2.3.0"
mockito = "3.5.15"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "android-constraintlayout"}
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }

[plugins]
gradle-android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
gradle-android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
gradle-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradle-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
